# Create a configMap called 'options' with the value var5=val5. Create a new nginx pod that loads
# the value from variable 'var5' in an env variable called 'option'
# $ kubectl create configmap options --from-literal=var5=val5
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: option
          valueFrom:
            configMapKeyRef:
              name: options
              key: var5
  restartPolicy: Never