# Create a PersistentVolumeClaim for this storage class, called mypvc, a request of 4Gi and an accessMode of ReadWriteOnce 
# and save it on pvc.yaml. Create it on the cluster. Show the PersistentVolumeClaims of the cluster. Show the 
# PersistentVolumes of the cluster
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  resources:
    requests:
      storage: 4Gi
  storageClassName: normal
  accessModes:
    - ReadWriteOnce