# Create busybox pod with two containers, each one will have the image busybox and will run the 'sleep 3600' command. 
# Make both containers mount an emptyDir at '/etc/foo'. Connect to the second busybox, write the first column of 
# '/etc/passwd' file to '/etc/foo/passwd'. Connect to the first busybox and write '/etc/foo/passwd' file to standard output. 
# Delete pod.
# $ kubectl exec busybox -c busybox2 -it /bin/sh
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    name: busybox
spec:
  volumes:
    - name: myvolume
      emptyDir: {}
  containers:
  - name: busybox
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600;"]
    volumeMounts:
      - name: myvolume
        mountPath: /etc/foo
  - name: busybox2
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600;"]
    volumeMounts:
      - name: myvolume
        mountPath: /etc/foo