---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-envconfig
spec:
  containers:
  - name: busybox
    image: busybox
    args: [/bin/sh, -c, env]
    env:
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: log-level-config
          key: log_level
