---
apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: redis-config-vol
      mountPath: /redis-master
    - name: redis-data-vol
      mountPath: /redis-master-data
  volumes:
  - name: redis-config-vol
    configMap:
      name: redis-configmap
  - name: redis-data-vol
    emptyDir: {}
