# Create the YAML for an nginx pod that runs with the UID 101
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  securityContext:
    runAsUser: 101
  containers:
    - name: nginx
      image: nginx
  restartPolicy: Never
