# Create a busybox pod that echoes 'hello world' and then exits
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - "echo"
      args:
        - "hello world"
