apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-storage
  labels:
    app: mysql
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: normal
  accessModes:
    - ReadWriteMany