apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-persistent-storage
  labels:
    app: wordpress
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany