# Create an nginx pod with a liveness probe that just runs the command 'ls'.
# Save its YAML in pod.yaml. Run it, check its probe status, delete it.
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  containers:
    - name: nginx
      image: nginx
      livenessProbe:
        exec:
          command: ["ls"]
  restartPolicy: Never