apiVersion: v1
kind: Service
metadata:
  name: ingress
  namespace: ingress-space
spec:
  selector:
    name: nginx-ingress
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
