# Convert the ClusterIP to NodePort and find the NodePort port. Hit it using Node's IP. 
# Delete the service and the pod
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80
  type: NodePort